### ISSUE TITLE
NoMethodError Exception: undefined method 'v1' for #<Twilio::REST::Api::V2010::AccountContext::NotificationList:0x007fe1830d9190>

### ISSUE THREAD

**Issue by kingreza** [TwilioDevEd/notifications-quickstart-ruby#1]
line 28 in `index.rb` has the following:

``` ruby
# Reference a valid notification service
service = client.notifications.v1.services(
  settings['TWILIO_NOTIFICATION_SERVICE_SID']
)
```

When we post /register from the android app we get

```
2016-09-20 18:23:38 - NoMethodError - undefined method `v1' for #<Twilio::REST::Api::V2010::AccountContext::NotificationList:0x007fe3c0d749d8>:
    index.rb:28:in `block in <main>'
```

digging deeper showed that the `client.notifications` object created earlier does not have a v1 method

`(byebug) client.notifications.v1.services
*** NoMethodError Exception: undefined method 'v1' for #<Twilio::REST::Api::V2010::AccountContext::NotificationList:0x007fe1830d9190>`

we are using 
`gem 'twilio-ruby', '~> 5.0.0.rc2'`

and have setup our config.yml

**Comment by kingreza** [comment]
Turns out we were using `5.0.0.rc17` for `twilio-ruby` and with that version of the gem the v1 method has been removed. Once we forced using `5.0.0.rc5` it worked. I guess this app slightly outdated

**Comment by jefflinwood** [comment]
Thank you for the issue - I updated the sample app - the change was from notifications to notify. Thanks again!
